### ISSUE TITLE
Suggestion: Can we add custom message.

### ISSUE THREAD

**Issue by saurabhgayali** [pratiksharm/pay-via-upi#3]
The tool is excellent. It is just that I can use the same tool to ask for payments instead of asking for Donation.
In such case a simple message "Add custom money for payment and send me a screenshot at my number".

This will not only extend the functionality but probably increase the potential users for the tool. 
A simple message in parameters to write on it or change button text. I know it can be written externally too by coding but non coders perhaps would be main target and they could really use this feature.

**Comment by biomathcode** [comment]
Custom Message will work either i have to force people to create an account on my platform or I send Message by Whatsapp if we take the mobile numbers as UPI . I would require to store people data in a database to do that. That was not the aim of the project when I started it. UPI is secure by itself. The funds are debited only when they get transferred from one account to another. 


Also, I don't want people to expose their phone number. With the UPI Id, only thing anyone can know is their name. With the phone number is just too much insecure. 

Tool was created for the anonymous donations only. If you have better solution do let me know. 

Having a Secular payment gateway is a very difficult task. Even Razorpay can't be [trusted](https://www.business-standard.com/article/companies/hackers-steal-rs-7-3-cr-in-831-transactions-over-three-months-from-razorpay-122052001659_1.html). 

Thanks for the Issue. I will be closing it.

**Comment by saurabhgayali** [comment]
Custom message just for the display so that the same system can be use for payments also instead of just donation..
i am not talking about any sms system.
